### ISSUE TITLE
Control panel save quirks

### ISSUE THREAD

**Issue by websmyth** [silentzco/statamic-mailchimp#48] opened 2020-11-09 10:43 UTC
Two small issues I’ve noticed:

**1. Consent field**
`'consent_field' => 'consent',` appears in `mailchimp.php` even if the user toggles consent `off`. I’d guess this wouldn’t happen if the user clears `consent_field` first, but haven’t tested that and it might not be obvious. 

When the file saves like this, the CP config page loads without pulling in any of the data saved in `mailchimp.php`

~~**2. Disable opt-in**~~
~~a) There’s no option to toggle this setting in the CP.~~
~~b) When adding multiple forms, `'disable_opt_in' => false,` only appears on the first form, not subsequent ones.~~

~~It would be useful to be able to toggle this in the CP on a per-form basis (I think that’s how the Statamic 2 version of this plugin worked?). Rare use case perhaps, but users with multiple audiences this may need to be toggled on/off per form.~~

**Comment by edalzell** [comment] 2020-11-10 22:02
Thanks for this Dave, I'll get these sorted. In the meantime, setting the config in the file should work fine.

**Comment by websmyth** [comment] 2020-11-10 22:14
All good! 🙌

**Comment by edalzell** [comment] 2020-11-11 00:48
@websmyth which version of Mailchimp are you talking about?

**Comment by edalzell** [comment] 2020-11-11 00:51
> Two small issues I’ve noticed:
> 
> **1. Consent field**
> `'consent_field' => 'consent',` appears in `mailchimp.php` even if the user toggles consent `off`. I’d guess this wouldn’t happen if the user clears `consent_field` first, but haven’t tested that and it might not be obvious.

I was unable to reproduce this, please try on the latest version (released soon) and let me know if this still occurs

**Comment by edalzell** [comment] 2020-11-11 00:51
> **2. Disable opt-in**
> a) There’s no option to toggle this setting in the CP.
> b) When adding multiple forms, `'disable_opt_in' => false,` only appears on the first form, not subsequent ones.
> 
> It would be useful to be able to toggle this in the CP on a per-form basis (I think that’s how the Statamic 2 version of this plugin worked?). Rare use case perhaps, but users with multiple audiences this may need to be toggled on/off per form.

This will be in the next release.

**Comment by websmyth** [comment] 2020-11-11 08:03
Amazing. Will confirm `1`, too. 🙌

**Comment by edalzell** [comment] 2020-11-12 00:53
> > **2. Disable opt-in**
> > a) There’s no option to toggle this setting in the CP.
> > b) When adding multiple forms, `'disable_opt_in' => false,` only appears on the first form, not subsequent ones.
> > It would be useful to be able to toggle this in the CP on a per-form basis (I think that’s how the Statamic 2 version of this plugin worked?). Rare use case perhaps, but users with multiple audiences this may need to be toggled on/off per form.
> 
> This will be in the next release.

In 2.3.1

**Comment by edalzell** [comment] 2022-03-07 02:06
Closing due to lack of confirmation.

Please re-open if still an issue.

**Closed** 2022-03-07 02:06 UTC
