### ISSUE TITLE
Error when editing maichimp config in CPanel

### ISSUE THREAD

**Issue by maxi032** [silentzco/statamic-mailchimp#89] opened 2023-02-14 14:14 UTC
When I access mysite.test/cpanel/mailchimp/config/edit I get an error:
```
Statamic\Fields\Fields::addValues(): Argument #1 ($values) must be of type array, string given, called in /usr/share/nginx/html/vendor/statamic/cms/src/Fieldtypes/Grid.php on line 103
```

Environment:

Laravel Version: 9.51.0
PHP Version: 8.2.1
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: mysite.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
edalzell/forma: 1.2.1
silentz/mailchimp: 2.10
spatie/statamic-responsive-images: 2.15.2
statamic/eloquent-driver: 1.2.0
withcandour/aardvark-seo: 2.0.30

**Comment by robdekort** [comment] 2023-02-14 14:15
Hey this seems related to #87. Erin is having a hard time replicating this issue. If you could list the steps to take to reproduce this maybe he can figure it out. 

In the meantime if you configure the addon via the php config file you should be able to get it working.

**Comment by maxi032** [comment] 2023-02-14 15:30
I reinstalled the package and now everything works fine.

**Comment by maxi032** [comment] 2023-02-15 07:42
This morning the error is back.
There is no difference compared to yesterday, other than I restarted the docker containers.
I am using docker with WSL2 for local dev.

**Comment by maxi032** [comment] 2023-02-15 12:14
@robdekort Do you think that maybe you could share your config?
From what I have seen you have more experience with it than me :)
What I want is to be able to subcribe users.
I have 'disable_opt_in' => true, and marketing permisions are not set.
merge_fields are also not set.

**Comment by robdekort** [comment] 2023-02-15 12:37
Yeah this is mine.
```php
<?php

return [

    'api_key' => env('MAILCHIMP_APIKEY'),

    /*
     * If you want to add to your mailchimp audience when a user registers, set this to `true`
     */
    'add_new_users' => false,

    'users' => [
        'id' => 'N7nO2Y4X',
        'check_consent' => true,
        'consent_field' => 'consent',
        'disable_opt_in' => false,
        'interests_field' => 'interests',
        'marketing_permissions_field' => 'gdpr',
        'marketing_permissions_field_ids' => [
            [
                'field_name' => null,
                'id' => null,
            ],
        ],
        'merge_fields' => [
            [
                'id' => 'F7dsYCaa',
            ],
        ],
        'primary_email_field' => 'email',
    ],

    /*
     * The form submissions to add to your Mailchimp Audiences
     */
    'forms' => [
        [
            'id' => 'AtdVzs5H',
            'form' => 'contact',
            'check_consent' => true,
            'consent_field' => 'newsletter',
            'disable_opt_in' => false,
            'marketing_permissions_field_ids' => [
                [
                ],
            ],
            'merge_fields' => [
                [
                    'id' => 'aHm9yh5l',
                    'field_name' => 'first_name',
                    'tag' => 'FNAME',
                ],
                [
                    'id' => 'ld8yk7ai',
                    'field_name' => 'last_name',
                    'tag' => 'LNAME',
                ],
                [
                    'id' => 'ld8yk7or',
                    'field_name' => 'company',
                    'tag' => 'COMPANY',
                ],
            ],
            'primary_email_field' => 'email',
            'audience_id' => '$$$$',
        ],
        [
            'id' => 'AtdVzs5H',
            'form' => 'newsletter',
            'check_consent' => true,
            'consent_field' => 'consent',
            'disable_opt_in' => false,
            'marketing_permissions_field_ids' => [
                [
                ],
            ],
            'merge_fields' => [
                [
                    'id' => 'aHm9yh5l',
                    'field_name' => 'first_name',
                    'tag' => 'FNAME',
                ],
                [
                    'id' => 'ld8yk7ai',
                    'field_name' => 'last_name',
                    'tag' => 'LNAME',
                ],
                [
                    'id' => 'ld8yk7or',
                    'field_name' => 'company',
                    'tag' => 'COMPANY',
                ],
            ],
            'primary_email_field' => 'email',
            'audience_id' => '$$$$',
        ]
    ],
];
```
I've hid the audience id's.

**Comment by robdekort** [comment] 2023-02-15 18:31
Def. a duplicate of #87

**Comment by edalzell** [comment] 2023-02-18 23:14
Dupe of #87

**Closed by edalzell** 2023-02-18 23:14 UTC
